spring.application.name=manager
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=myuser
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

ingestion.rest.send.url=http://localhost:8087/api/v1/events

spring.security.oauth2.client.registration.agentsmith.client-id=a8Q5LWqrhyQQVqhtau4lSiqJFl0uod2b
spring.security.oauth2.client.registration.agentsmith.client-secret=gnQ0QhhTgteChAO7fGAxH2vxxAWlvBY2urdpxHj9qq3IemBGWHXJeL2ItriAlqlC
spring.security.oauth2.client.registration.agentsmith.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.agentsmith.redirect-uri=http://localhost:8080/login/oauth2/code/agentsmith
spring.security.oauth2.client.registration.agentsmith.scope=openid,profile,email
spring.security.oauth2.client.registration.agentsmith.client-authentication-method=client_secret_basic
spring.security.oauth2.client.provider.agentsmith.issuer-uri=https://dev-t3aad5tt8o4dhzde.us.auth0.com/